# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Maven verify

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        runner:
          # https://github.com/ankane/setup-mongodb?tab=readme-ov-file#versions
          - os: ubuntu-24.04
            mongo: 8
          - os: windows-2022
            mongo: 5
          - os: macos-14
            mongo: 8
        java-version:
          - 21
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v2
    with:
      runner: ${{ matrix.runner.os }}
      java-version: ${{ matrix.java-version }}
      # db settings must match testing profile
      db-type: mongodb
      db-version: ${{ matrix.runner.mongo }}  # see https://github.com/ankane/setup-mongodb/issues/6
